### ISSUE TITLE
Updating buildpack version causes CC's post-start to fail

### ISSUE THREAD

**Issue by gdankov** [SUSE/scf#2560]
### Description

Updating buildpack version causes `api-group` to fail when restarted. 

What we get before we update a buildpack:

```
❯❯ cf buildpacks                                                                                                                      «k8s | jax-conf:scf»
Getting buildpacks...

buildpack               position   enabled   locked   filename                                           stack
staticfile_buildpack    1          true      false    staticfile-buildpack-v1.4.42.1-1.1-006475c6.zip
nginx_buildpack         2          true      false    nginx-buildpack-v1.0.11.1-1.1-35853e75.zip
java_buildpack          3          true      false    java-buildpack-v4.19.1.1-e77a8d4f.zip
ruby_buildpack          4          true      false    ruby-buildpack-v1.7.38.1-1.1-89e27de4.zip
nodejs_buildpack        5          true      false    nodejs-buildpack-v1.6.49.1-1.1-db13bdef.zip
go_buildpack            6          true      false    go-buildpack-v1.8.35.1-1.1-f3363ca3.zip
python_buildpack        7          true      false    python-buildpack-v1.6.32.1-1.1-70284bad.zip
php_buildpack           8          true      false    php-buildpack-v4.3.75.1-1.1-d8175284.zip
binary_buildpack        9          true      false    binary-buildpack-v1.0.32.1-1.1-abe9e1d8.zip
dotnet-core_buildpack   10         true      false    dotnet-core-buildpack-v2.2.10.1-1.1-6ae54c7b.zip
```

Then we ran:
```
cf update-buildpack ruby_buildpack -p https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.7.41/ruby-buildpack-cflinuxfs3-v1.7.41.zip
```

What we get after updating the buildpack:
```
❯ cf buildpacks                                                                                                                       «k8s | jax-conf:scf»
Getting buildpacks...

buildpack               position   enabled   locked   filename                                           stack
staticfile_buildpack    1          true      false    staticfile-buildpack-v1.4.42.1-1.1-006475c6.zip
nginx_buildpack         2          true      false    nginx-buildpack-v1.0.11.1-1.1-35853e75.zip
java_buildpack          3          true      false    java-buildpack-v4.19.1.1-e77a8d4f.zip
ruby_buildpack          4          true      false    ruby-buildpack-cflinuxfs3-v1.7.41.zip              cflinuxfs3
nodejs_buildpack        5          true      false    nodejs-buildpack-v1.6.49.1-1.1-db13bdef.zip
go_buildpack            6          true      false    go-buildpack-v1.8.35.1-1.1-f3363ca3.zip
python_buildpack        7          true      false    python-buildpack-v1.6.32.1-1.1-70284bad.zip
php_buildpack           8          true      false    php-buildpack-v4.3.75.1-1.1-d8175284.zip
binary_buildpack        9          true      false    binary-buildpack-v1.0.32.1-1.1-abe9e1d8.zip
dotnet-core_buildpack   10         true      false    dotnet-core-buildpack-v2.2.10.1-1.1-6ae54c7b.zip
```

After that we restarted the api-group pod.
Logs from post-start in api-group:
```
+ tail -n+3
+ grep -v post-start
+ grep --silent -viw 'accessible\|running'
+ read -r f
++ find /var/vcap/jobs/authorize-internal-ca/bin /var/vcap/jobs/bpm/bin /var/vcap/jobs/cloud_controller_ng/bin /var/vcap/jobs/global-properties/bin -name post-start
+ echo bash /var/vcap/jobs/cloud_controller_ng/bin/post-start
+ bash /var/vcap/jobs/cloud_controller_ng/bin/post-start
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ CC_JOB_DIR=/var/vcap/jobs/cloud_controller_ng
+ CONFIG_DIR=/var/vcap/jobs/cloud_controller_ng/config
+ CC_PACKAGE_DIR=/var/vcap/packages/cloud_controller_ng
+ export CLOUD_CONTROLLER_NG_CONFIG=/var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml
+ CLOUD_CONTROLLER_NG_CONFIG=/var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml
+ export BUNDLE_GEMFILE=/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/Gemfile
+ BUNDLE_GEMFILE=/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/Gemfile
+ source /var/vcap/jobs/cloud_controller_ng/bin/ruby_version.sh
++ source /var/vcap/packages/ruby-2.5.5-r0.10.0/bosh/runtime.env
+++ export PATH=/var/vcap/packages/ruby-2.5.5-r0.10.0/bin:/bin:/usr/bin:/sbin:/usr/sbin
+++ PATH=/var/vcap/packages/ruby-2.5.5-r0.10.0/bin:/bin:/usr/bin:/sbin:/usr/sbin
+++ export GEMRC=/var/vcap/packages/ruby-2.5.5-r0.10.0/bosh/gemrc
+++ GEMRC=/var/vcap/packages/ruby-2.5.5-r0.10.0/bosh/gemrc
+ source /var/vcap/packages/capi_utils/syslog_utils.sh
+ source /var/vcap/packages/capi_utils/monit_utils.sh
++ basename /var/vcap/jobs/cloud_controller_ng/bin/post-start
+ tee_output_to_sys_log cloud_controller_ng.post-start
+ declare log_name=cloud_controller_ng.post-start
+ exec
+ exec
++ tee -a /dev/fd/63
+++ logger -p user.info -t vcap.cloud_controller_ng.post-start.stdout
++ prepend_datetime
++ awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }'
++ tee -a /dev/fd/63
+++ logger -p user.error -t vcap.cloud_controller_ng.post-start.stderr
awk: option `-W interactive' unrecognized, ignored
++ prepend_datetime
++ awk -W interactive '{ system("echo -n [$(date +\"%Y-%m-%d %H:%M:%S%z\")]"); print " " $0 }'
awk: option `-W interactive' unrecognized, ignored
[2019-07-15 11:37:17+0000] + main
[2019-07-15 11:37:17+0000] + install_buildpacks
[2019-07-15 11:37:17+0000] + pushd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
[2019-07-15 11:37:17+0000]+ flock -n 9
+ exit 1
 + chpst -u vcap:vcap bundle exec rake buildpacks:install
[2019-07-15 11:37:29+0000] rake aborted!
[2019-07-15 11:37:29+0000] VCAP::CloudController::Jobs::Runtime::BuildpackInstallerFactory::StacklessBuildpackIncompatibilityError: VCAP::CloudController::Jobs::Runtime::BuildpackInstallerFactory::StacklessBuildpackIncompatibilityError
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/app/jobs/runtime/buildpack_installer_factory.rb:108:in `find_buildpack_to_update'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/app/jobs/runtime/buildpack_installer_factory.rb:45:in `block in plan'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/app/jobs/runtime/buildpack_installer_factory.rb:44:in `each'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/app/jobs/runtime/buildpack_installer_factory.rb:44:in `plan'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:48:in `block in install'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:47:in `each'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/lib/cloud_controller/install_buildpacks.rb:47:in `install'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/lib/tasks/buildpacks.rake:6:in `block (3 levels) in <top (required)>'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/lib/cloud_controller/background_job_environment.rb:15:in `setup_environment'
[2019-07-15 11:37:29+0000] /var/vcap/packages/.src/730a6deb20401a4fd8a3c90c94409fbfd1f8e6351d316b47c14f5ce1d0fd0d92/cloud_controller_ng/lib/tasks/buildpacks.rake:5:in `block (2 levels) in <top (required)>'
[2019-07-15 11:37:29+0000] /var/vcap/packages/cloud_controller_ng/gem_home/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
[2019-07-15 11:37:29+0000] /var/vcap/packages/ruby-2.5.5-r0.10.0/bin/bundle:30:in `block in <main>'
[2019-07-15 11:37:29+0000] /var/vcap/packages/ruby-2.5.5-r0.10.0/bin/bundle:22:in `<main>'
[2019-07-15 11:37:29+0000] Tasks: TOP => buildpacks:install
[2019-07-15 11:37:29+0000] (See full trace by running task with --trace)

```

### Steps to reproduce

1. Deploy SCF
1. Update a buildpack
1. Restart the `api-group` pod
1. `api-group` stuck on `1/2     Running`

### What was expected to happen

`api-group` should start up successfully.

### What actually happened

`api-group`'s post-start script fails.

Best regards,
Georgi

**Comment by jandubois** [comment]
The problem is that you are replacing a built-in stackless buildpack with a stackful one.

Every time the cloud controller starts it executes https://github.com/cloudfoundry/cloud_controller_ng/blob/master/lib/tasks/buildpacks.rake to install the bundled buildpacks (if they are not already there).

Unfortunately the rake tasks goes through the same validation code as the interactive `update-buildpack` command and will throw an error when it tries to reinstall the bundled buildpack.

Actually, when I tried to repro using the `cf` CLI, I didn't get an error, but the buildpack name remained locked to the `cflinuxfs3` stack name even after I updated it with a stackless buildpack:

```
$ cf update-buildpack ruby_buildpack -p https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.7.41/ruby-buildpack-cflinuxfs3-v1.7.41.zip
$ cf update-buildpack ruby_buildpack -p https://cf-buildpacks.suse.com/ruby-buildpack-v1.7.40.1-1.1-32939548.zip
$ cf buildpacks
Getting buildpacks...

buildpack               position   enabled   locked   filename                                           stack
...
ruby_buildpack          4          true      false    ruby-buildpack-v1.7.40.1-1.1-32939548.zip          cflinuxfs3
```

I'll follow up with the CAPI team because I think this behaviour is wrong. Given that you had not locked the new buildpack, it should have reverted the buildpack back to the bundled version without raising an error when you restated the `api-group` pod. And if you had locked the buildpack, then it should just have left it in place.

# Workarounds

I've verified that simply locking the updated stackful buildpack does not work; it will also throw an error during an `api-group` pod restart.

## Use the SUSE stackless buildpack

```
cf update-buildpack ruby_buildpack -p https://cf-buildpacks.suse.com/ruby-buildpack-v1.7.41.1-1.1-c4cd5fed.zip
cf update-buildpack ruby_buildpack --lock
```

Note that you have to `--lock` any updated bundled buildpacks. Otherwise your changes will be reverted any time a CC instance is started.

## Don't re-use the builtin name

```
cf update-buildpack ruby_buildpack --disable
cf create-buildpack ruby_cflinuxfs3 https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.7.41/ruby-buildpack-cflinuxfs3-v1.7.41.zip 1 --enable
```

# Caveat

I seem to remember running into issues with bundler version mismatches when upgrading to ruby_buildpack 1.7.4; you may need to edit your `Gemfile.lock` in your applications when you switch to that buildpack. Can't remember the details; maybe it was something I did wrong.

**Comment by jandubois** [comment]
> I'll follow up with the CAPI team

I've filed https://github.com/cloudfoundry/cloud_controller_ng/issues/1393

**Comment by gdankov** [comment]
Awesome, thank you!

**Comment by jandubois** [comment]
> I seem to remember running into issues with bundler version mismatches when upgrading to ruby_buildpack 1.7.41

@gdankov Looks like the bundler issue has been fixed (worked around) in 1.7.42, which was released just now: https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.42

You should find a corresponding stackless SUSE version at https://github.com/SUSE/cf-ruby-buildpack/releases once all the additional SUSE assets have been built by CI (assuming the results will pass BRATS).

**Comment by jandubois** [comment]
> once all the additional SUSE assets have been built by CI

Stackless buildpack now available from https://github.com/SUSE/cf-ruby-buildpack/releases/tag/v1.7.42.1
